---
default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/backplane/pre-commit-rust-hooks
    rev: v1.1.0
    hooks:
      - id: fmt
      - id: check
      - id: clippy
      - id: test
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []