
[package]
name = "rexegy"
version = "0.1.0"
authors = ["James Cape <jamescape777@gmail.com"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/jcape/rexegy"
rust-version = "1.85"

[dependencies]

[workspace]
resolver = "2"
members = [
    "sys",
]

[workspace.package]
version = "0.1.0"
authors = ["James Cape <jamescape777@gmail.com"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/jcape/rexegy"
rust-version = "1.85"